version: '3'
services:
  api:
    image: 'com.pillar/spring-demo'
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"

  mongodb:
    image: 'mongo:latest'
    restart: always
    ports:
      - "27017:27017"
