version: '3'
services:
  api:
    image: 'com.pillar/spring-demo'
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
    networks:
      - spring-demo-bridge

  mongodb:
    image: 'mongo:latest'
    restart: always
    networks:
      - spring-demo-bridge
    ports:
      - "27017:27017"

networks:
  spring-demo-bridge:
    external: true