version: '3'
services:
  api:
    image: 'com.pillar/spring-demo'
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
    networks:
      - aclifton

  mongodb:
    image: 'mongo:latest'
    restart: always
    networks:
      - aclifton
    ports:
      - "27017:27017"

networks:
  aclifton:
    external: true